// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDNA.Repositories.ThuNTN.Models;

public partial class TestResultsThuNtn
{
    public int TestResultThuNtnid { get; set; }

    public int OrderId { get; set; }

    public int ResultVersion { get; set; }

    public string ResultSummary { get; set; }

    public string ResultDetail { get; set; }

    public string ResultFileUrl { get; set; }

    public string IssuedBy { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string ResultStatus { get; set; }

    public virtual TestOrdersThuNtn? Order { get; set; }
}