// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDNA.GraphQLAPIService.ThuNTN.Models;

public partial class TestOrdersThuNtn
{
    public int TestOrderThuNtnid { get; set; }

    public int UserId { get; set; }

    public string ServiceType { get; set; }

    public string SampleMethod { get; set; }

    public DateTime? AppointmentAt { get; set; }

    public string Location { get; set; }

    public string Status { get; set; }

    public bool? IsResultOnline { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<TestResultsThuNtn> TestResultsThuNtns { get; set; } = new List<TestResultsThuNtn>();

    public virtual Account? User { get; set; }
}  